import { ClerkProvider } from '@clerk/nextjs'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import LeftSideBar from '@/components/Global/LeftSideBar'
import BottomBar from '@/components/Global/BottomBar'
import { dark } from '@clerk/themes'
import { Toaster } from '@/components/ui/toaster'
import { LoaderProvider } from '@/components/ui/LoaderContext'
import Loader from '@/components/ui/Loader'
import TopBar from '@/components/Global/TopBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Threads | Home",
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>
      <LoaderProvider>
        <html lang="en">
          <meta name="theme-color" content="#121417" />
          <body className={`${inter.className} bg-dark-1 custom-scrollbar`}>

            <main className='flex'>
              <TopBar/>
              <LeftSideBar />
              <section className='pt-20 lg:pt-24 w-full pb-20 md:pb-10 pl-4 pr-4 lg:pl-10 lg:pr-10 max-w-4xl mr-auto ml-auto'>
                {children}
              </section>
            </main>
            <BottomBar />
            <Loader />
            <Toaster />
            
          </body>
        </html>
      </LoaderProvider>
    </ClerkProvider>
  )
}
