import { ClerkProvider } from '@clerk/nextjs'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { dark } from '@clerk/themes'
import { Toaster } from '@/components/ui/toaster'
import { LoaderProvider } from '@/components/ui/LoaderContext'
import Loader from '@/components/ui/Loader'
import LeftSideBar from '@/components/Global/LeftSideBar'
import { ChatProvider } from '@/Context/ChatContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Threads | Chat",
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>
      <LoaderProvider>
        <ChatProvider>
          <html lang="en">
            <meta name="theme-color" content="#121417" />
            <body className={`${inter.className} bg-dark-1 custom-scrollbar`}>

              <main className='flex'>
                {/* <TopBar/> */}
                <LeftSideBar isChat={true} />
                <section className='w-full max-h-screen overflow-hidden'>
                  {children}
                </section>
              </main>
              <Loader />
              <Toaster />

            </body>
          </html>
        </ChatProvider>
      </LoaderProvider>
    </ClerkProvider>
  )
}
